version: '3.8'

services:
  lipreader:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ${DATA_PATH:-./data}:/app/data  # Mount data directory
      - ${CHECKPOINT_PATH:-./checkpoints}:/app/checkpoints  # Mount checkpoints
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - TF_FORCE_GPU_ALLOW_GROWTH=true
      - TF_GPU_ALLOCATOR=cuda_malloc_async
      - CUDA_CACHE_DISABLE=0
      - CUDA_CACHE_MAXSIZE=2147483648  # 2GB cache size
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu] 